[[fastlowess]]
arch = "aarch64"
git-tree-sha1 = "3bd9680aea04ffe55372bc567d56d73abc12dc46"
os = "macos"

    [[fastlowess.download]]
    sha256 = "828519169fcd446947dd9de5b235665e81eb0eaf7eaad664321eaa3366463bc2"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.aarch64-apple-darwin.tar.gz"
[[fastlowess]]
arch = "aarch64"
git-tree-sha1 = "e80ec42f5e120dcb5afcd927fe6a5a677921dbb7"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "6130dcb2b7a2aef52947e124b2ef5a2f98ebb47774a2321c3d0f1b249931ffc3"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.aarch64-linux-gnu.tar.gz"
[[fastlowess]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c4d277ae83374098dc792e0d9ff32bbd1d1b646"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "7326ce0ae4b4afaa7201c835159dec92770ae3ad5775e0d36a2b17dc9fdd8b0b"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.armv6l-linux-gnueabihf.tar.gz"
[[fastlowess]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd7126878d0dc01476a730a8b5470c5482024754"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "a2967c81316c8081019d090b828214a7bf49981c66c4196734e39f9532a0bd31"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.armv7l-linux-gnueabihf.tar.gz"
[[fastlowess]]
arch = "i686"
git-tree-sha1 = "6afde0076e3f8eea36dae92652290741070b96a6"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "ef3df4ccd4ab840d5d5db0f54046ddc20b3fc317cb1d6fbcbe2481a742223783"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.i686-linux-gnu.tar.gz"
[[fastlowess]]
arch = "powerpc64le"
git-tree-sha1 = "391bc8db6e58d942236cd8eef7f10e69f616ddd4"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "77840b6dc3b0e826ae5a0a6dd1853064c4d39796aac354a0a928db84f4cb6945"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.powerpc64le-linux-gnu.tar.gz"
[[fastlowess]]
arch = "x86_64"
git-tree-sha1 = "95065ad269184e7458da2cf043a19b66057bcc38"
os = "macos"

    [[fastlowess.download]]
    sha256 = "35c5d9accd1cacfaac257eef53ad03bfab7024c2e0f3e96db6e21db7ae61d348"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.x86_64-apple-darwin.tar.gz"
[[fastlowess]]
arch = "x86_64"
git-tree-sha1 = "81b5b4d5f9f1eed4ae6fca69136fe2682a46ccd2"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "07a01d9af97d31085619d9f386a802326b503b19a8234e9d0cd4226204cef9a3"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.x86_64-linux-gnu.tar.gz"
[[fastlowess]]
arch = "x86_64"
git-tree-sha1 = "6105b07309e704dff7cd5ff4e3f627e6698e852c"
os = "windows"

    [[fastlowess.download]]
    sha256 = "3a1205a15c0fe82f9b54c0076308ab59bfd9dc5b9e70b2dd70ddff5b5b55b0a4"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v0.99.9+0/fastlowess.v0.99.9.x86_64-w64-mingw32.tar.gz"
